In [1]:
import cv2

In [4]:
grey_img = cv2.imread('original.png', 0)

In [8]:
grey_img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
cv2.imwrite('newimg.png', grey_img)

True

In [11]:
grey_img[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [12]:
grey_img.T

array([[187, 198, 209],
       [158, 125, 134],
       [104, 255, 255],
       [121, 255,  97],
       [143, 147, 182]], dtype=uint8)

In [14]:
for i in grey_img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [18]:
import numpy as np
ims = np.hstack([grey_img, grey_img])
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
imv = np.vstack([grey_img, grey_img])
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [20]:
hs = np.hsplit(ims, 5)
hs

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8),
 array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8),
 array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8),
 array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8),
 array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]

In [21]:
vs = np.vsplit(imv, 3)
vs

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]